<a href="https://colab.research.google.com/github/SREENIVASAN-PRASANTH/AI-Integrated_Career_Development_Platform_for_Students/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch as tp
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(tp.__version__)

2.3.1+cu121


In [ ]:
!nvidia-smi

Thu Aug  1 14:53:03 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
###creating tensors
scalar = tp.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back as python integer
scalar.item()

7

In [ ]:
#vector
vector = tp.tensor([7,7])
vector

tensor([7, 7])

vector.ndim

```
# This is formatted as code
```




In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [3]:
matrix = tp.tensor([[1,2,3],[4,5,6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
matrix.ndim

2

In [6]:
matrix[0]

tensor([1, 2, 3])

In [ ]:
matrix.shape

torch.Size([2, 3])

In [20]:
TENSOR = tp.tensor([[[[1,2],
                    [4,5],
                    [7,8]],[[1,2],[3,4],[5,6]]]])
TENSOR.shape

torch.Size([1, 2, 3, 2])

In [23]:
random_tensor = tp.rand(size = (3,4))
random_tensor

tensor([[0.6655, 0.3787, 0.4345, 0.1821],
        [0.5537, 0.2480, 0.0041, 0.8179],
        [0.5893, 0.0032, 0.3994, 0.8838]])

In [28]:
random_tensor2 = tp.rand(size = (244,244,3))

random_tensor2.ndim

3

In [32]:
zeroes_tensors = tp.zeros(size = (1,2,3))
zeroes_tensors
zeroes_tensors.dtype

torch.float32

In [36]:
ones = tp.ones(size = (1,5,2))
ones
ones.dtype

torch.float32

In [38]:
one_to_ten = tp.arange(start = 1, end = 10, step = 2)
one_to_ten

tensor([1, 3, 5, 7, 9])

In [39]:
zeroes_to_ten = tp.zeros_like(input = one_to_ten)
zeroes_to_ten

tensor([0, 0, 0, 0, 0])

In [49]:
float_32_tensor = tp.tensor([1,2,3],
                            dtype = tp.float16,
                            device = "cpu",
                            requires_grad = False)
float_32_tensor.dtype

torch.float16

In [46]:
float_32_tensor.device

device(type='cpu')